name: EzOffice Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pyinstaller-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'  # Adjust based on your version
          spec: 'src/build.spec'  # Path to your .spec file
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'EzOffice'  # Custom name for the executable
          options: '--onefile --name "EzOffice" --windowed'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: EzOffice Executable
          path: dist/  # Default output directory of PyInstaller
